name: Symfony CI

on:
  push:
    
  pull_request:
    branches: 
     -master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer_install
      run: echo "installling packges ..."
           composer install --dev
      
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: unit_test
      run:
          echo "running unit test ..."
          vendor/bin/simple-phpunit tests
    - name: code_sniffer
      run: vendor/bin/phpcs
