version: '3'

networks:
    c4d:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/c4d/backend
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - c4d

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/c4d/backend
        networks:
            - c4d

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            #MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - c4d

    # node
    # node-service:
    #     image: node:latest
    #     container_name: node-container
    #     volumes:
    #         - ./app:/var/www/project
    #     working_dir: /var/www/project
    #     networks:
    #         - masdar