default_platform(:android)
platform :android do
  desc "Submit a new build to alpha Track on Play"
  lane :alpha do
    gradle(
      task: "assemble",
      build_type: 'Debug'
    )
    gradle(
      task: "assemble",
      build_type: 'Profile'
    )
    gradle(
      task: "assemble",
      build_type: 'Release'
    )
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end
end